trigger:
  branches:
    include:
    - master
    - validate/*
    - release/*
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/
    - .github/

parameters:
- name: includeMacOS
  displayName: Build on macOS
  type: boolean
  default: false # macOS is often bogged down in Azure Pipelines

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU
  codecov_token: 28f9f3c0-c497-4acf-8113-4a23b8c99950
  ci_feed: /e08c98c0-63d6-4dc6-80ca-944e4deaf3d2
  NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages

jobs:
- template: azure-pipelines/build.yml
  parameters:
    includeMacOS: ${{ parameters.includeMacOS }}
